# Run Fastfetch
if command -v fastfetch &> /dev/null; then
  fastfetch
fi

# Load zsh_aliases 
if [ -f ~/.config/zsh/zsh_aliases ]; then
  source ~/.config/zsh/zsh_aliases
fi


# ! Ambient variables
export PATH=$HOME/.local/bin:$HOME/.local/bin:$PATH


# Load oh-my-posh and zoxide
eval "$(oh-my-posh init zsh --config $HOME/.config/ohmyposh/config.toml)"
eval "$(zoxide init --cmd cd zsh)"


# Load "asdf" plugin
source ~/.config/asdf/asdf.sh


# Load Zsh plugins (Auto Suggestions and Syntax Hightlighting)
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# History Config
HISTFILE=~/.config/zsh/zsh_history
HISTSIZE=1000
SAVEHIST=1000

