console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  black = '#000000'
  blue = '#4B95E9'
  green = '#50fa7b'
  orange = '#F07623'
  red = '#ff0043'
  white = '#E0DEF4'
  yellow = '#F3AE35'

[transient_prompt]
  template = '<p:red>λ </>'
  foreground = 'p:black'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '<p:white>Run in</p:white> <#ff0043>{{ .FormattedMs }}</> '
    foreground = '#ffffff'
    type = 'executiontime'
    style = 'plain'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '<p:red>{{ .UserName }}</> <p:white>on</>'
    foreground = '#ff0043'
    type = 'session'
    style = 'plain'

  [[blocks.segments]]
    template = ' {{.Parent}}{{.Path}}'
    foreground = '#ff0043'
    type = 'path'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}<p:yellow>*</>{{ end }}</><red>{{ if gt .Behind 0 }}⇣{{ end }}</><green>{{ if gt .Ahead 0 }}⇡{{ end }}</>'
    foreground = 'p:white'
    background = 'transparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = 'λ'
    foreground = 'p:white'
    type = 'text'
    style = 'plain'
