version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "executiontime"
style = "plain"
foreground = "#ffffff"
template = "<p:white>Run in</p:white> <#ff0043>{{ .FormattedMs }}</> "

[executiontime.properties]
threshold = 500
style = "austin"
always_enabled = true
display_distro_name = true

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "session"
style = "plain"
content = "\uE0B0"
template = "<p:red>{{ .UserName }}</> <p:white>on</>"
foreground = "#ff0043"

[[blocks.segments]]
type = "path"
template = " {{.Parent}}{{.Path}}"
foreground = "#ff0043"
NameLength = 0

[blocks.segments.properties]
style = 'folder'

# ! Git
[[blocks.segments]]
type = "git"
style = "plain"
foreground = "p:white"
background = "transparent"
template = " {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}<p:yellow>*</>{{ end }}</><red>{{ if gt .Behind 0 }}⇣{{ end }}</><green>{{ if gt .Ahead 0 }}⇡{{ end }}</>"
[blocks.segments.properties]
branch_icon = ""
commit_icon = "@"
fetch_status = true

# ! Send
[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true
[[blocks.segments]]
type = 'text'
style = 'plain'
template = "λ"
foreground = 'p:white'

[transient_prompt]
template = '<p:red>λ </>'
foreground = 'p:black'
Duration = 0
NameLength = 0

[palette]
black = '#000000'
blue = '#4B95E9'
green = '#50fa7b'
orange = '#F07623'
red = '#ff0043'
white = '#E0DEF4'
yellow = '#F3AE35'
