if command -v fastfetch &> /dev/null; then
  fastfetch
fi

# ! Ambient variables
export PATH=$HOME/.local/bin:$HOME/.local/bin:$PATH

# Load oh-my-posh and zoxide
eval "$(oh-my-posh init zsh --config $HOME/.config/ohmyposh/config.toml)"
eval "$(zoxide init --cmd cd zsh)"

# Load "asdf" plugin
source ~/.config/asdf/asdf.sh

# ! Load Modules
# Load Auto Suggestions and Syntax Hightlighting on zsh
source ~/.config/zsh/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
source ~/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# History Config
HISTFILE=~/.config/zsh/zsh_history
HISTSIZE=1000
SAVEHIST=1000


# ! Alias
# Clear history
alias clear-history="rm -f ~/.config/zsh/zsh_history && kill -9 $$"

# Replace with some better alternatives
alias ls="lsd --recursive --depth 1 --group-dirs=first"
alias cat="bat --style=auto"


# Common use
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"
alias bsprestart="bspc wm -r"
# Cleanup orphaned packages
alias clean-up="sudo pacman -Rns $(pacman -Qtdq)"


# Start Xampp
alias xampp="execute_commands"
execute_commands() {
  sudo su -c "nohup /opt/lampp/manager-linux-x64.run > /dev/null 2>&1 & disown; exit" && exit
}

