#! /bin/sh


# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄
bspc monitor DP-1 -d I II III IV V VI
bspc monitor HDMI-1 -d VII
xrandr --output DP-1 --auto --primary --output HDMI-1 --auto --pos 0x1920

